name: Auto Retry Terraform Oracle

on:
  schedule:
    - cron: '*/10 * * * *' # Tự chạy lại mỗi 10 phút
  workflow_dispatch: # Cho phép bấm chạy thủ công ngay lập tức

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup OCI Key File
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path: "~/.oci/oci_api_key.pem"
        run: terraform apply -auto-approve
